<?php

/**
 * @file
 * Hooks and callbacks for this module.
 */

define('ISLANDORA_IMAGE_ANNOTATION_VIEW', 'view image annotations');
define('ISLANDORA_IMAGE_ANNOTATION_CREATE', 'create image annotations');

/**
 * Implements hook_menu().
 */
function islandora_image_annotation_menu() {
  $items = array();
  $items['admin/islandora/tools/image_annotation'] = array(
    'title' => 'Image annotation',
    'description' => 'Configure the image annotation module.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_image_annotation_admin_settings_form'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['islandora/anno/test'] = array(
    'page callback' => 'islandora_image_annotation_build_manifest',
    'type' => MENU_CALLBACK,
    'access arguments' => array(ISLANDORA_IMAGE_ANNOTATION_VIEW),
    'file' => 'includes/build_streams.inc',
  );

  $items['islandora/anno/setup'] = array(
    'page callback' => 'islandora_image_annotation_canvas_setup',
    'type' => MENU_CALLBACK,
    'access arguments' => array(ISLANDORA_IMAGE_ANNOTATION_VIEW),
    'file' => 'includes/callbacks.inc',
  );

  $items['islandora/anno/add_annotation'] = array(
    'page callback' => 'islandora_image_annotation_add_annotation',
    'type' => MENU_CALLBACK,
    'access arguments' => array(ISLANDORA_IMAGE_ANNOTATION_CREATE),
    'file' => 'includes/callbacks.inc',
  );

  $items['islandora/anno/get_urns'] = array(
    'page callback' => 'islandora_image_annotation_shared_get_annotation_pids',
    'type' => MENU_CALLBACK,
    'access arguments' => array(ISLANDORA_IMAGE_ANNOTATION_VIEW),
    'file' => 'includes/callbacks.inc',
  );

  $items['islandora/anno/get_annotation'] = array(
    'page callback' => 'islandora_image_annotation_shared_get_annotation',
    'type' => MENU_CALLBACK,
    'access arguments' => array(ISLANDORA_IMAGE_ANNOTATION_VIEW),
    'file' => 'includes/callbacks.inc',
  );
  $items['islandora/anno/delete_annotation'] = array(
    'page callback' => 'islandora_delete_annotation',
    'type' => MENU_CALLBACK,
    'access arguments' => array(ISLANDORA_IMAGE_ANNOTATION_CREATE),
    'file' => 'includes/callbacks.inc',
  );

  $items['islandora/anno/serve'] = array(
    'page callback' => 'islandora_image_annotation_islandora_serve',
    'type' => MENU_CALLBACK,
    'access arguments' => array(ISLANDORA_IMAGE_ANNOTATION_VIEW),
    'file' => 'includes/build_streams.inc',
  );
  $items['islandora/anno/update_annotation'] = array(
    'page callback' => 'islandora_image_annotation_canvas_update_annotation',
    'type' => MENU_CALLBACK,
    'access arguments' => array(ISLANDORA_IMAGE_ANNOTATION_CREATE),
    'file' => 'includes/callbacks.inc',
  );

  $items['islandora/anno/solr/title/terms/%'] = array(
    'page callback' => 'islandora_image_annotation_get_title_terms',
    'page arguments' => array(5),
    'type' => MENU_CALLBACK,
    'access arguments' => array(ISLANDORA_IMAGE_ANNOTATION_CREATE),
    'file' => 'includes/callbacks.inc',
  );

  $items['islandora/anno/mads/%'] = array(
    'page callback' => 'islandora_image_annotation_get_mads_as_json',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array(ISLANDORA_IMAGE_ANNOTATION_CREATE),
    'file' => 'includes/callbacks.inc',
  );

  $items['islandora/object/%islandora_object/annotation'] = array(
    'title' => 'Image Annotation',
    'page callback' => 'islandora_image_annotation_view',
    'page arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'islandora_image_annotation_access',
    'access arguments' => array(2),
  );

  $items['islandora/object/%islandora_object/annotation_test'] = array(
    'title' => 'Image Annotation',
    'page callback' => 'islandora_image_annotation_view_test',
    'page arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'islandora_image_annotation_access',
    'access arguments' => array(2),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function islandora_image_annotation_permission() {
  return array(
    ISLANDORA_IMAGE_ANNOTATION_VIEW => array(
      'title' => t('View image annotations'),
      'description' => t('View image annotations.'),
    ),
    ISLANDORA_IMAGE_ANNOTATION_CREATE => array(
      'title' => t('Create image annotations'),
      'description' => t('Create image Annotations'),
    ),
  );
}

/**
 * Determines whether or not to show this modules tab.
 *
 * @global object $user
 *
 * @param FedoraObject $fedora_object
 *   A FedoraObject.
 *
 * @return bool
 *   Whether the user has access or not.
 */
function islandora_image_annotation_access($fedora_object) {
  if (!isset($fedora_object)) {
    return FALSE;
  }

  $cmodel_list = variable_get('islandora_annotation_mappings');
  foreach ($fedora_object->models as $model) {
    if (isset($cmodel_list[$model])) {
      return user_access(ISLANDORA_IMAGE_ANNOTATION_VIEW);
    }
  }
  return FALSE;
}

/**
 * Implements hook_theme().
 */
function islandora_image_annotation_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_image_annotation' => array(
      'template' => 'theme/islandora-image-annotation',
      'variables' => array('objects' => NULL),
      'file' => 'theme/theme.inc',
    ),
    'islandora_image_annotation_dialog' => array(
      'template' => 'theme/islandora-image-annotation-dialog',
      'variables' => array('object' => NULL),
      'file' => 'theme/theme.inc',
    ),
    'islandora_image_annotation_list' => array(
      'template' => 'theme/islandora-image-annotation-list',
      'variables' => array('object' => NULL),
      'file' => 'theme/theme.inc',
    ),
    'islandora_image_annotation_canvas' => array(
      'template' => 'theme/islandora-image-annotation-canvas',
      'variables' => array('object' => NULL),
      'file' => 'theme/theme.inc',
    ),
    // @deprecated theme function.
    'islandora_image_annotation_view' => array(
      'template' => 'theme/islandora-image-annotation-view',
      'variables' => array('islandora_objects' => NULL),
      'file' => 'theme/theme.inc',
    ),
    // @deprecated theme function.
    'islandora_anno_list_pane' => array(
      'template' => 'theme/islandora-list-pane',
    ),
    // @deprecated theme function.
    'islandora_anno_image_pane' => array(
      'template' => 'theme/islandora-img-pane',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * The image annotation view.
 *
 * @param FedoraObject $object
 *   A FedoraObject.
 *
 * @return string
 *   The marked up output.
 */
function islandora_image_annotation_view($object) {
  return theme('islandora_image_annotation_view', array('islandora_object' => $object));
}

/**
 * The image annotation view.
 *
 * @param FedoraObject $object
 *   A FedoraObject.
 *
 * @return string
 *   The marked up output.
 */
function islandora_image_annotation_view_test($object) {
  return theme('islandora_image_annotation', array('object' => $object));
}



/**
 * Implements hook_islandora_required_objects().
 */
function islandora_image_annotation_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_image_annotation');
  // OAC Content Model.
  $oac_content_model = $connection->repository->constructObject('islandora:OACCModel');
  $oac_content_model->owner = 'fedoraAdmin';
  $oac_content_model->label = 'Islandora Annotation CModel';
  $oac_content_model->models = 'fedora-system:ContentModel-3.0';

  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $oac_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_image_annotation_ds_composite_model.xml", FALSE);
  $oac_content_model->ingestDatastream($datastream);

  return array(
    'islandora_image_annotation' => array(
      'title' => 'Islandora image annotations',
      'objects' => array(
        $oac_content_model,
      ),
    ),
  );
}
