<?php

/**
 * @file
 * islandora_image_annotation.install
 */

/**
 * Implements hook_install().
 *
 * @see islandora_image_annotation_islandora_required_objects()
 */
function islandora_image_annotation_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  // Install solution pack object(s).
  islandora_install_solution_pack('islandora_image_annotation');
}

/**
 * Implements hook_uninstall().
 */
function islandora_image_annotation_uninstall() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  $variables = array(
    'islandora_annotation_mappings',
    'islandora_annotation_enforce_taxonomy',
    'islandora_annotation_optimized',
    'islandora_annotation_type_search_field',
    'islandora_image_annotation_stroke_width',
    'islandora_image_annotation_use_entity_tagging',
    'islandora_image_annotation_use_title_vocabulary',
    'islandora_image_annotation_title_search_field',
    'islandora_image_annotation_genre_search_field',
    'islandora_image_annotation_datastreams',
  );
  array_walk($variables, 'variable_del');
  // Uninstall callback.
  islandora_install_solution_pack('islandora_image_annotation', 'uninstall');
}

/**
 * Renamed / fixed variables.
 */
function islandora_image_annotation_update_7100() {
  // Rename and fix the existing variables.
  $rename_variable = function($old, $new, $default) {
    variable_set($new, variable_get($old, $default));
    variable_del($old);
  };
  $rename_variable('annotation_type_search_field', 'islandora_annotation_type_search_field', 'mads_categories_s');
  $rename_variable('image_annotation_annotation_stroke_width', 'islandora_image_annotation_stroke_width', '.3 .6 .9 1.2 1.5');
  $rename_variable('annotation_use_title_vocabulary', 'islandora_annotation_type_search_field', FALSE);
  $rename_variable('annotation_title_search_field', 'islandora_image_annotation_title_search_field', 'mads_titles_sv');
  $rename_variable('annotation_genre_search_field', 'islandora_image_annotation_genre_search_field', 'mads_genre_it');
}
